// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbxrigrarweuoavlqyta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBieHJpZ3JhcndldW9hdmxxeXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1ODkzMjUsImV4cCI6MjA2OTE2NTMyNX0.dyVDlwJ3BMfwnPIrQDo7hwh7doME-blak83Uo-lp8sg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});